# Generated by Django 4.1 on 2022-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekmenutype',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
