# Generated by Django 4.1 on 2022-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_menu', '0003_alter_weekmenu_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekmenu',
            name='type',
        ),
        migrations.AddField(
            model_name='weekmenu',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='weekmenu',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='weekmenu',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Завтрак'),
        ),
    ]
