# Generated by Django 4.1 on 2022-08-16 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок блока')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Загловок')),
                ('text', models.CharField(max_length=255, verbose_name='Описание')),
                ('phone_1', models.CharField(max_length=15, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(max_length=15, verbose_name='Телефон 2')),
                ('email_1', models.CharField(max_length=50, verbose_name='Email 1')),
                ('email_2', models.CharField(max_length=50, verbose_name='Email 2')),
                ('instagram', models.URLField(max_length=100, verbose_name='Инстаграм')),
                ('copywrite', models.CharField(max_length=100, verbose_name='Копирайт')),
            ],
            options={
                'verbose_name': 'Основные',
                'verbose_name_plural': 'Основные',
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Пункт меню')),
                ('url', models.CharField(help_text='Не менять', max_length=50, verbose_name='Ссылка меню')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Порядок')),
                ('draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('id_menu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='id_menu', to='main.main')),
            ],
            options={
                'verbose_name': 'Фото блока',
                'verbose_name_plural': 'Фото блока',
            },
        ),
    ]
