# Generated by Django 4.1 on 2022-08-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'Пункты меню', 'verbose_name_plural': 'Пункты меню'},
        ),
    ]
