# Generated by Django 4.1 on 2022-08-17 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mainmenu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('person', models.CharField(max_length=50, verbose_name='Колличество гостей')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('time', models.CharField(max_length=50, verbose_name='Колличество гостей')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявки с формы бронирования',
                'verbose_name_plural': 'Заявки с формы бронирования',
            },
        ),
    ]
