# Generated by Django 4.1 on 2022-08-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmenu',
            options={'verbose_name': 'Настройки меню'},
        ),
    ]
