# Generated by Django 4.1 on 2022-08-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок баннера')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголвок баннера')),
                ('button_title', models.CharField(max_length=50, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='review/', verbose_name='Фото отзыва')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Порядок')),
                ('id_photo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='id_photo', to='slider.mainbanner')),
            ],
            options={
                'verbose_name': 'Изображения баннера',
                'verbose_name_plural': 'Изображения баннера',
            },
        ),
    ]
