# Generated by Django 4.1 on 2022-08-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='photo',
            field=models.ImageField(null=True, upload_to='review/', verbose_name='Фото баннера'),
        ),
    ]
