# Generated by Django 4.1 on 2022-08-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutChefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название блока')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Настройки блока',
            },
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Должность')),
                ('descr', models.CharField(max_length=255, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('instagram', models.URLField(max_length=100, verbose_name='Инстаграм')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Порядок')),
                ('draft', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Шефы',
                'verbose_name_plural': 'Шефы',
            },
        ),
    ]
