# Generated by Django 4.1 on 2022-08-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название блока')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Заголовок блока')),
                ('text', models.CharField(max_length=255, verbose_name='Описание')),
                ('video_prew', models.ImageField(upload_to='image/', verbose_name='Фото превью видео')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='image/', verbose_name='Фото блока')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Порядок')),
                ('id_photo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='id_photo', to='about.about')),
            ],
            options={
                'verbose_name': 'Фото блока',
                'verbose_name_plural': 'Фото блока',
            },
        ),
    ]
